-- https://school.programmers.co.kr/learn/courses/30/lessons/131529
SELECT * FROM PRODUCT;

-- 문자열 잘라 GROUP BY 하기
SELECT
    SUBSTRING(PRODUCT_CODE,1,2) AS CATEGORY,
    COUNT(SUBSTRING(PRODUCT_CODE,1,2)) AS PRODUCTS
FROM
    PRODUCT
GROUP BY
    SUBSTRING(PRODUCT_CODE,1,2)
ORDER BY
    CATEGORY ASC
;